import { z } from "zod";

/**
 * Utility = self-contained mini-app generated by an agent (or installed from
 * GitHub) that lives outside Reflex source and talks to Reflex through a
 * sandboxed Host API. The contract here is the source of truth for what an
 * agent must emit, what the on-disk manifest looks like, and what the audit
 * log captures.
 */

export const UTILITY_SCOPES = ["global", "project"] as const;
export type UtilityScope = (typeof UTILITY_SCOPES)[number];

export const HOST_API_TASKS = ["chat", "quick", "rag", "embed"] as const;

const IdSchema = z
  .string()
  .min(1)
  .max(80)
  .regex(
    /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/,
    "id must be kebab-case (e.g. furniture-gen)",
  );

export const PermissionsSchema = z
  .object({
    llm: z
      .object({
        tasks: z.array(z.enum(HOST_API_TASKS)).default([]),
      })
      .optional(),
    kb: z
      .object({
        read: z.boolean().optional(),
        write: z.boolean().optional(),
        kinds: z.array(z.string()).optional(),
      })
      .optional(),
    fs: z
      .object({
        sandbox: z.literal(true),
      })
      .optional(),
    web: z
      .object({
        fetch: z
          .object({
            domains: z.array(z.string()).default([]),
          })
          .optional(),
        search: z.boolean().optional(),
      })
      .optional(),
    audit: z
      .object({
        write: z.literal(true).optional(),
      })
      .optional(),
    workers: z
      .object({
        enabled: z.literal(true),
        maxConcurrent: z.number().int().min(1).max(8).default(1).optional(),
      })
      .optional(),
    /**
     * Lets the utility spawn ephemeral orchestrator agents via
     * `reflex.agent.invoke({prompt})`. The agent runs one full turn in
     * an isolated topic that gets deleted after harvest — utility never
     * sees the topic in the sidebar. Off by default.
     */
    agent: z
      .object({
        invoke: z.literal(true),
      })
      .optional(),
    /**
     * Lets the utility list / read / run project workflows from inside
     * its sandbox. Workflows are the user's "linear recipes" — utilities
     * can compose them like an SDK once granted.
     */
    workflow: z
      .object({
        read: z.boolean().optional(),
        run: z.boolean().optional(),
      })
      .optional(),
    /**
     * Image generation + web image search. Generated/downloaded files
     * land in the project's `<root>/.reflex/assets/images/` and are
     * served via `/api/images/<rootId>/<sha>.<ext>` — stable per-root
     * URLs that move with the project.
     */
    images: z
      .object({
        /** Allow `reflex.images.generate({prompt, ...})`. */
        generate: z.boolean().optional(),
        /** Allow `reflex.images.search({query, ...})` (Unsplash/Pexels). */
        search: z.boolean().optional(),
        /**
         * Allow `reflex.images.attach({sourceUrl})` — downloads a remote
         * URL into per-root storage. The source URL must be on the
         * utility's `web.fetch.domains` whitelist.
         */
        attach: z.boolean().optional(),
        /**
         * External image hosts the utility's iframe may DISPLAY via
         * `<img src>`. Each entry is appended to the iframe CSP's
         * `img-src` (as `https://<host>`), so the browser loads them
         * directly — no proxy, no server fetch. Plain hostnames only,
         * optional leading `*.` wildcard. This is a display grant, not
         * a network-fetch grant (that's `web.fetch.domains`): the user
         * vouches for the host the same way, but the request goes
         * browser → host, not through Reflex.
         */
        domains: z
          .array(
            z
              .string()
              .regex(
                /^(\*\.)?[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/i,
                "must be a bare hostname, optional leading '*.'",
              ),
          )
          .max(20)
          .optional(),
      })
      .optional(),
    /**
     * Read-only access to the cross-Space session search index (journal
     * entries + topic transcripts, FTS5). Lets the utility answer "did
     * the user mention X before?" without holding its own history.
     */
    sessions: z
      .object({
        search: z.boolean().optional(),
      })
      .optional(),
  })
  .default({});

/**
 * A user-managed secret slot the utility declares in its manifest. The agent
 * sees these declarations (key + label + description) but **never** the
 * values — values are filled by the user via the UI and read at runtime
 * through `reflex.secrets.get({key})`.
 */
export const SecretDeclarationSchema = z.object({
  key: z
    .string()
    .min(1)
    .max(64)
    .regex(
      /^[A-Z][A-Z0-9_]*$/,
      "secret key must be UPPER_SNAKE_CASE (e.g. OPENAI_API_KEY)",
    ),
  label: z.string().min(1).max(120),
  description: z.string().max(2_000).default(""),
  required: z.boolean().default(false),
});

export type SecretDeclaration = z.infer<typeof SecretDeclarationSchema>;

export const ServerActionSchema = z.object({
  name: z
    .string()
    .min(1)
    .max(64)
    .regex(/^[a-zA-Z_][a-zA-Z0-9_]*$/, "action name must be a JS identifier"),
  entry: z
    .string()
    .min(1)
    .regex(/^[A-Za-z0-9_\-./]+\.ts$/, "entry must be a relative .ts path"),
  // Up to 10 min — AI-heavy actions (article + diagrams + quiz) realistically
  // need a few minutes; UI shows a spinner. Floor at 1s to catch fat-finger 0s.
  timeoutMs: z.number().int().min(1_000).max(600_000).default(30_000),
});

export const UtilitySourceSchema = z.object({
  type: z.enum(["agent", "github", "archive", "mcp", "builtin"]),
  /** Free-form provenance ID, e.g. "agent:<topicId>:<agentId>" or
   *  "github:owner/repo@sha". */
  origin: z.string().optional(),
  fetchedAt: z.string(),
  installedBy: z.string().optional(),
});

export const ManifestSchema = z.object({
  id: IdSchema,
  name: z.string().min(1).max(120),
  description: z.string().max(2_000).default(""),
  version: z
    .string()
    .regex(/^\d+\.\d+\.\d+(?:[-+][\w.]+)?$/, "version must be semver"),
  author: z.string().max(120).optional(),
  homepage: z.string().url().optional(),
  icon: z
    .string()
    .max(64_000)
    .regex(
      /^(?:lucide:[A-Za-z0-9_-]+|data:image\/(?:png|svg\+xml|jpeg);base64,[A-Za-z0-9+/=]+)$/,
      "icon must be 'lucide:Name' or a base64 data URL",
    )
    .optional(),
  category: z.string().max(64).optional(),
  ui: z.string().min(1).max(120).default("ui.tsx"),
  serverActions: z.array(ServerActionSchema).default([]),
  secrets: z.array(SecretDeclarationSchema).default([]),
  /**
   * Third-party npm packages the utility imports. Key = package name,
   * value = an exact version (pin — ranges work but lose
   * reproducibility). At BUILD time esbuild resolves a bare import of a
   * listed package to `https://esm.sh/<pkg>@<ver>` and inlines it into
   * the bundle (cached on disk). Nothing is fetched at runtime — the
   * iframe CSP stays `connect-src 'none'`. A bare import NOT listed here
   * (and not React/host) is a build error, so this list is the
   * dependency allowlist the user reviews at install. Pure-JS/ESM only;
   * node-native packages won't work in action bundles.
   */
  dependencies: z
    .record(
      z
        .string()
        .regex(
          /^(?:@[a-z0-9][\w.-]*\/)?[a-z0-9][\w.-]*$/i,
          "must be an npm package name",
        ),
      z.string().min(1).max(64),
    )
    .refine((d) => Object.keys(d).length <= 30, "at most 30 dependencies")
    .default({}),
  /**
   * IDs of MCP servers (from the global registry at
   * `~/.reflex/mcp/servers.json`) this utility wants to call. Listed here
   * so the host can enforce per-utility access — `reflex.mcp.call({server,
   * tool, args})` rejects anything not in this list. UI shows the list
   * during install so the user can review.
   */
  mcpServers: z.array(z.string().min(1).max(64)).default([]),
  permissions: PermissionsSchema,
  source: UtilitySourceSchema.optional(),
  /**
   * Optional compact preview the utility renders as a widget on the
   * project dashboard, so the user sees its top-line value without
   * opening the full page. Declarative — `kind` matches one of the
   * standard widget kinds, `data` is the matching payload. The utility
   * keeps it fresh via `reflex.cards.update({snapshot})` from inside
   * its full UI (or from a server-action triggered by a workflow).
   *
   * NEW utilities should always declare a card. The install dialog
   * shows a warning when absent.
   */
  card: z
    .object({
      kind: z.enum([
        "markdown",
        "news-list",
        "link-list",
        "kpi",
        "checklist",
        "quote",
        "kb-pinned",
        "progress",
        "image",
        "stat-table",
        "map",
        "action-list",
      ]),
      title: z.string().min(1).max(120).optional(),
      description: z.string().max(280).optional(),
      /** Initial / fallback data shown before the first live refresh. */
      data: z.record(z.string(), z.unknown()).default({}),
      /**
       * Name of a server action (from `serverActions`) that returns a
       * FRESH card snapshot — `{kind, data, title?, description?}`. When
       * set, Reflex calls it to pull live data: on dashboard view and on
       * the `refresh` cadence below. The action runs in a worker with the
       * utility's host API, so it can read `reflex.kb.list`,
       * `reflex.tasks.list`, etc. Without it, the card only updates when
       * the utility pushes via `reflex.cards.update` from its own iframe.
       */
      action: z
        .string()
        .regex(/^[a-zA-Z_][a-zA-Z0-9_]*$/, "action must be a serverActions name")
        .optional(),
      /**
       * Background refresh cadence for the card action. "manual" (default)
       * = only refresh on dashboard view + explicit Refresh. Ignored when
       * `action` is absent.
       */
      refresh: z.enum(["manual", "hourly", "daily", "weekly"]).optional(),
    })
    .optional(),
  /**
   * Utilities can extend the host. When installed into a Space, a
   * utility's `extensions` are auto-registered: new slash-commands
   * appear in the chat palette, declared skills become loadable via
   * `/skill <id>`, and `systemPromptAddendum` is appended to every
   * chat system prompt in that Space.
   *
   * This is what makes `rflx-task-board` add `/task` + the
   * `<<reflex:task-create>>` protocol without touching Reflex core —
   * future utilities can do the same.
   */
  extensions: z
    .object({
      slashCommands: z
        .array(
          z.object({
            id: z
              .string()
              .min(1)
              .max(64)
              .regex(/^[a-z][a-z0-9-]*$/),
            trigger: z
              .string()
              .min(1)
              .max(40)
              .regex(/^[a-z][a-z0-9-]*$/),
            label: z.string().min(1).max(60),
            description: z.string().max(280),
            icon: z.string().min(1).max(40),
            kind: z.enum(["agent-mode", "direct"]),
            usage: z.string().max(200).default(""),
            allowEmpty: z.boolean().default(false),
            /**
             * For `kind: "agent-mode"` — markdown block appended to the
             * chat system prompt when this command fires. May use
             * `{payload}` and `{language}` placeholders.
             */
            promptBlock: z.string().max(20_000).optional(),
            /**
             * For `kind: "direct"` — name of a serverAction declared in
             * this manifest to invoke when the user runs the command.
             */
            directAction: z.string().max(120).optional(),
          }),
        )
        .default([]),
      skills: z
        .array(
          z.object({
            id: z
              .string()
              .min(1)
              .max(64)
              .regex(/^[a-z][a-z0-9-]*$/),
            title: z.string().min(1).max(120),
            description: z.string().max(280),
            instructions: z.string().min(1).max(50_000),
            workflowId: z.string().max(120).optional(),
          }),
        )
        .default([]),
      /**
       * Utility-provided workflows. Materialised at runtime — never
       * written to the Space's `.reflex/workflows/` directory, so
       * uninstalling the utility cleanly removes them. The scheduler
       * picks up `hourly`/`daily`/`weekly` triggers; users can still
       * fire manual ones from the workflows page.
       *
       * If a project-stored workflow with the same `id` exists, IT
       * wins — user explicitly forked the utility's workflow.
       */
      workflows: z
        .array(
          z.object({
            id: z
              .string()
              .min(1)
              .max(64)
              .regex(/^[a-z][a-z0-9-]*$/),
            label: z.string().min(1).max(120),
            description: z.string().max(280).optional(),
            trigger: z.enum(["manual", "hourly", "daily", "weekly"]),
            steps: z
              .array(
                z.object({
                  id: z.string().min(1).max(64),
                  kind: z.string().min(1).max(40),
                  label: z.string().min(1).max(120),
                  params: z.record(z.string(), z.unknown()).default({}),
                }),
              )
              .min(1)
              .max(20),
          }),
        )
        .default([]),
      systemPromptAddendum: z.string().max(20_000).optional(),
    })
    .default({ slashCommands: [], skills: [], workflows: [] }),
});

export type Manifest = z.infer<typeof ManifestSchema>;
export type Permissions = z.infer<typeof PermissionsSchema>;
export type ServerAction = z.infer<typeof ServerActionSchema>;
export type UtilitySource = z.infer<typeof UtilitySourceSchema>;

/** Files map produced by an agent / fetched from GitHub before installation. */
export const InstallFilesSchema = z
  .record(z.string(), z.string())
  .superRefine((files, ctx) => {
    if (!("manifest.json" in files || files["manifest.json"])) {
      // manifest is passed separately; only validate that paths are safe
    }
    for (const path of Object.keys(files)) {
      if (path.startsWith("/") || path.includes("..")) {
        ctx.addIssue({
          code: "custom",
          message: `Unsafe file path: ${path}`,
        });
      }
    }
  });

export const InstallSpecSchema = z.object({
  scope: z.enum(UTILITY_SCOPES),
  rootId: z.string().optional(),
  manifest: ManifestSchema,
  files: InstallFilesSchema,
  source: UtilitySourceSchema,
});

export type InstallSpec = z.infer<typeof InstallSpecSchema>;

/** Surface metadata used by lists / sidebar — doesn't include file contents. */
export interface InstalledUtility {
  scope: UtilityScope;
  /** For project-scoped utilities, the registry root id this utility lives under. */
  rootId?: string;
  /** Absolute path to the utility's directory on disk. */
  dir: string;
  manifest: Manifest;
  bundleAvailable: boolean;
}

/**
 * Audit log entry. Append-only JSONL at `~/.reflex/audit/<YYYY-MM-DD>.jsonl`.
 * Every Host API call writes one "start" entry and one "end" entry sharing
 * the same `correlationId` so the UI can pair them up.
 */
export interface AuditEntry {
  ts: string;
  utilityId: string;
  scope: UtilityScope;
  /** Where the call came from. */
  channel: "iframe" | "worker" | "system";
  method: string;
  phase: "start" | "end";
  correlationId: string;
  /** A correlationId of a parent call — set when a server action triggers a nested host call. */
  parentCorrelationId?: string;
  args?: unknown;
  result?: unknown;
  error?: string;
  durationMs?: number;
}

export interface AuditFilter {
  utilityId?: string;
  method?: string;
  phase?: AuditEntry["phase"];
  status?: "ok" | "error";
}
